### ISSUE TITLE
[BUG] This happened almost for no reason that I could see.

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#125] opened 2020-09-15 19:34 UTC
![image](https://user-images.githubusercontent.com/61169385/93256169-f2c6dd80-f768-11ea-9d17-bcf466bd6a7e.png)

had to exit and open again

**Comment by pwang-boxlabs** [comment] 2020-09-17 10:36
is there any pattern that you can identify?

**Comment by dyuan-boxlabs** [comment] 2020-09-25 16:06
ill debug this a big, i will close it if i cant reproduce it

**Comment by dyuan-boxlabs** [comment] 2020-09-27 02:20
cant recreate it, closing

**Closed by dyuan-boxlabs** 2020-09-27 02:20 UTC
Labels: bug
